#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

server_url="https://piston-data.mojang.com/v1/objects/05e4b48fbc01f0385adb74bcff9751d34552486c/server.jar"
server_sha1=$(echo "$server_url" | cut -d'/' -f6) #get the server file hash

cd /data/

if [ ! -f /data/minecraft_server.jar ] || [[ `echo "$server_sha1 *minecraft_server.jar" | sha1sum -c -` != "minecraft_server.jar: OK" ]]
then
    echo "Downloading/Updating minecraft_server.jar"
    curl $server_url -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

java -Xmx2G -jar minecraft_server.jar --nogui

